---
apiVersion: v1
kind: Satefulset
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLables:
      app: app-database
  template:
    metadata:
      lables:
        app: app-database
    spec:
      containers:
        - name: cdbont
          image: saikumar1903/phpapp:dbimage
          ports:
            - containerPort: 3306
        #secret Intergration
          envFrom:
            - sceretRef:
              name: bankapp-db-secret
        #Resource Quota
          resources:
            requests: 
              cpu: "100m"
              memory: "128Mi"
            limits: 
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: pvc-1
              mountPath: /var/lib/mysql

          volumeClaimTemplates:
            - metadata:
                name: pvc-1
              spec: 
                accessMode:
                  - ReadWriteOnce
                resource:
                  requests:
                    storage: 2Gi
